### PR TITLE
Complete one app rails-react project with webpack

### PR DESCRIPTION
**Pull request by principlebrothers**
## Completed Project
In this project I achieved the following 
- [x] Implemented a connection between a Ruby on Rails back-end and React front-end.
- [x] Understood the pros and cons of different approaches of connecting Ruby on Rails back-end with React front-end.

### CODE REVIEW

**Comment by prolajumokeoni** [comment]
Hi @principlebrothers 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that  does not follow proper Gitflow and does not have the updated microverse readme template,

Kindly use the updated version  of the microverse [readme](https://github.com/microverseinc/readme-template) template for your readme, 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by principlebrothers** [comment]
@prolajumokeoni, thank you for the review. I have fix the `README.md` and the git-flow now.

**Review by Davidosky007 — COMMENTED** [review]
Hi @principlebrothers 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
invalide
## Invalid Code Review Request


You have submitted a project, that doesn't follow the proper [Gitflow pattern](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md), Kindly create a pull request to compare your feature branch with the development branch and submit the link to that pull request via your Dashboard  

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by principlebrothers** [comment]
Hello @Davidosky007, can you please explain it to me feather on the git-flow because, I have read the documentation and I followed by working on feature branches before merging it to the `dev` branch

**Comment by Davidosky007** [comment]
> Hello @Davidosky007, can you please explain it to me feature on the git-flow because, I have read the documentation and I followed by working on feature branches before merging it to the `dev` branch 

Your pull request should be opened from your feature into your dev branch

**Comment by MahmoudBakr23** [comment]
# Hi @principlebrothers 😃, 

As much as I appreciate your hard work on this project, I'm afraid that I can't perform a review on this pull request.

## **Invalid Submission**

- As explained to you, please make sure that the submitted PR is requesting a merge into `dev` from `feature` branch

_Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready._ 🙏

Cheers and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

<hr>

_Invalid Code Review Request does not count into the code reviews limit._

**Comment by principlebrothers** [comment]
@Davidosky007 and @MahmoudBakr23 I don't understand. There is no way I can added linter and make a pull request for it to be approved. I only have one pull request how then can I submit every feature  I develop?

**Comment by principlebrothers** [comment]
Please  help to understand  because  I don't  understand  the logic you are proposing.

**Comment by MahmoudBakr23** [comment]
@principlebrothers Can you see the main from dev on the picture down below!
Please make it dev from (any branch name)
Screenshot_2023-01-03-01-50-19-93_40deb401b9ffe8e1df2f1cc5ba480b12

**Comment by principlebrothers** [comment]
> @principlebrothers Can you see the main from dev on the picture down below! Please make it dev from (any branch name) Screenshot_2023-01-03-01-50-19-93_40deb401b9ffe8e1df2f1cc5ba480b12

@MahmoudBakr23 if I change `main` to `dev`, how do I maintain the same pull request because as soon I change the `dev` to something else, this pull request will close?

**Pull request closed without merging**
