### PR TITLE
Complete rails-react app

### PR DESCRIPTION
**Pull request by principlebrothers**

### CODE REVIEW

**Review by BenMukebo — CHANGES_REQUESTED** [review]
### Hi @principlebrothers,

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight 💪🏻
- No Linter errors :heavy_check_mark: 
- API endpoint for returning a random greeting was created. ✔️  
- Database table for storing different greetings was created. ✔️  
- There is a `Greeting` component. ✔️
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

- [x] You should  make sure the API endpoint for returning a random greeting works as expected. 💯 👍🏻   Actually your Gretting modals is empty, i suggest you create some random greeting!! You can use the seed for this 🤔 

Screenshot from 2023-01-03 03-24-42

- [ ] Great job so far, however, I It will be great for the `App` component to have a route that leads to the `Greeting` component. This is a major requirement for this project to be approved. ⬇️ and

- [ ] There should be a store, action and reducer that uses the url to the Rails API endpoint (as nothing is deployed here, it can be a placeholder) Actually you missed the redux part, please add this 👇🏻 Here are the project requirements

Screenshot from 2023-01-03 03-31-44




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principlebrothers** [comment]
I appreciate the feedback @BenMukebo. Nothing stops me from giving you 5 ⭐ . Also with the greetings, I think you have to add it to the database through the rails console since the base API is from from a local port.

**Review by mukhammadrizooff — APPROVED** [review]
Hi @principlebrothers, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principlebrothers** [comment]
Thanks for the review @mukhammadrizooff.

**Pull request merged**
